import {
  WORKSPACE_CONFIG_FILENAME,
  FLOW_BOOK_DIRNAME,
  FLOW_STORIES_DIRNAME,
} from './config-filenames.js'

// NOTE: packages/create-flowkit-app/index.js's write*Screen/writeDb/writeFlowplans
// functions hand-port this same demo content for standalone publishing (it can't
// import this file — see that file's own top-of-file comment on why). If you add
// or remove a demo page/chapter here, update it there too — page/chapter id naming
// has already drifted between the two (this file suffixes with -screen/-flow,
// create-flowkit-app doesn't), so don't rely on exact id matching to catch it.
// scripts/tests/scaffold-consistency.test.js checks structural shape (page/chapter
// counts), not full content or exact ids.
//
// NOTE on the demo buttons below having both an `id` and an onClick calling
// navigateTo(): two independent navigation conventions deliberately coexist
// on the same element.
//   1. The `id` matches a flowStory step's `on` field — FlowMaster.tsx's
//      handleContainerClick does event delegation over the whole screen
//      container during flow playback and advances the step from there.
//   2. onClick calls navigateTo(id) via useAppNav() (@flowkit-shared/utils),
//      which makes the button also work standalone (Screens tab, free
//      exploration) with no branching in the screen's own code. useAppNav()
//      internally picks FlowMaster's flow-aware navigateTo when this screen
//      is rendered inside a flow, or DashboardContext's otherwise — so
//      calling it unconditionally is always safe. (Older screens using
//      useDashboard() directly still need a manual `!isChapter &&` guard around
//      navigateTo() to avoid desyncing DashboardContext's view history from
//      FlowEngine's step index during flow playback — useAppNav() exists
//      specifically so new screens never have to write that guard.)
export function workspaceScaffold(name, kit = 'none', isStandalone = false, language = 'ts') {
  const kitCssImport =
    kit === 'none'
      ? ''
      : isStandalone
        ? `@import "@flowkit/kits/standalone/${kit}/index.css";`
        : `@import "@flowkit-kit/index.css";`

  const tokensCss =
    kit === 'none'
      ? `/* ${name} — Design Tokens */\n/* No kit selected — add your own CSS variables here. */\n:root {\n  /* --my-brand: #1a1a2e; */\n}\n`
      : isStandalone
        ? `/* ${name} — Design Tokens */\n/* Standalone kit: ${kit} — self-contained cascade, no shared components */\n${kitCssImport}\n\n/* ── Workspace-level overrides ─────────────────────────────────────────────\n   Override kit variables under [data-kit="${kit}"] here.\n   ────────────────────────────────────────────────────────────────────────── */\n[data-kit="${kit}"] {\n  /* --wf-font: "Inter", system-ui, sans-serif; */\n}\n`
        : `/* ${name} — Design Tokens */\n/* Kit base + theme + utilities — imported first; overrides below */\n${kitCssImport}\n\n/* ── Workspace-level overrides ─────────────────────────────────────────────\n   Override any --kit-* variable here to customise the active theme.\n   These always win over theme defaults (last write in cascade).\n   ────────────────────────────────────────────────────────────────────────── */\n:root {\n  /* --kit-brand: #1a1a2e; */\n  /* --kit-font:  "Inter", system-ui, sans-serif; */\n}\n`

  return workspaceScaffoldFiles(name, tokensCss, language)
}

function workspaceScaffoldFiles(name, tokensCss, language = 'ts') {
  const isJs = language === 'js'
  const sext = isJs ? 'js' : 'ts'
  return {
    [`index.${sext}`]: `// Workspace barrel — add shared exports here as needed.\n// The platform reads pages via the ${FLOW_BOOK_DIRNAME}/ glob; no router required.\n`,
    'lib/data/db.ts': `// Workspace mock database — all runtime state lives here.\n// Named exports are loaded into the platform db object on startup.\n// Reset via the simulator's "Reset Database" button.\n\nexport const user = {\n  id: 'usr_001',\n  name: 'Demo User',\n  email: 'demo@example.com',\n  plan: 'Free',\n}\n\nexport const items = [\n  { id: 1, title: 'First Item', desc: 'A sample item to demonstrate db reads.', status: 'active' },\n  { id: 2, title: 'Second Item', desc: 'Another item showing list rendering.', status: 'pending' },\n  { id: 3, title: 'Third Item', desc: 'More items can be added in db.ts.', status: 'active' },\n]\n`,
    'lib/data/simulator.tsx': `import { ControlAccordion, SimAction, SimControl } from '@flowkit-features/simulator/controls'\n\nexport default function WorkspaceSimulatorControls() {\n  return (\n    <>\n      <ControlAccordion label="User" defaultOpen>\n        <SimControl label="Name" bind="db.user.name" />\n        <SimControl label="Email" bind="db.user.email" />\n        <SimControl label="Plan" bind="db.user.plan" options={['Free', 'Pro', 'Enterprise']} />\n      </ControlAccordion>\n\n      <ControlAccordion label="Items">\n        <SimControl label="Items list" bind="db.items" />\n      </ControlAccordion>\n\n      <ControlAccordion label="Data">\n        <SimAction label="Reset Database" icon="Trash2" badgeColor="red" onClick={ctx => ctx.resetDb()} />\n      </ControlAccordion>\n    </>\n  )\n}\n`,
    'lib/design-system/tokens.css': tokensCss,
    [WORKSPACE_CONFIG_FILENAME]: `import { defineConfig } from '@flowkit-core/config'\n\nexport default defineConfig({\n  workspace: { name: '${name}' },\n  // Page loaded by default (cold load, device home button, reset-to-first)\n  // when no flowStory is active. Falls back to the first declared page when unset.\n  startPage: 'welcome-screen',\n  // Default device shell shown on load. Must match a DevicePreset.label from\n  // src/shared/components/devices (e.g. \"iPhone 16 Pro\"). Falls back to the\n  // platform default when unset or unrecognized.\n  defaultDevice: 'Compact',\n  // Default orientation on load. Ignored if the device doesn't support landscape.\n  defaultOrientation: 'portrait',\n  chapters: ['onboarding-flow', 'home-flow'],\n  pageOrder: {\n    'onboarding-flow': ['welcome-screen', 'setup-screen', 'ready-screen'],\n    'home-flow': ['home-screen', 'detail-screen'],\n  },\n})\n`,
    '.flowkit/components.json': `[]\n`,
    [`${FLOW_STORIES_DIRNAME}/onboarding-flow.ts`]: `import { defineFlow } from '@flowkit-core/config'\n\nexport default defineFlow({\n  id: 'onboarding-flow',\n  name: 'Onboarding Flow',\n  description: 'Guides the user through welcome, profile setup, and into the app.',\n\n  steps: [\n    { pageId: 'onboarding-flow-welcome-screen', on: 'get-started', actionNote: 'Taps Get Started' },\n    { pageId: 'onboarding-flow-setup-screen', on: 'continue', actionNote: 'Confirms profile and continues' },\n    { pageId: 'onboarding-flow-ready-screen', on: 'go-to-home', actionNote: 'Proceeds to home' },\n  ],\n})\n`,
    [`${FLOW_STORIES_DIRNAME}/home-flow.ts`]: `import { defineFlow } from '@flowkit-core/config'\n\nexport default defineFlow({\n  id: 'home-flow',\n  name: 'Home Flow',\n  description: 'Browse the item list and view a detail page.',\n  // Screen the device home button targets while this flowStory is playing.\n  // Overrides the workspace's startPage for the duration of playback.\n  homeScreen: 'home-screen',\n\n  steps: [\n    { pageId: 'home-flow-home-screen', on: 'item-1', actionNote: 'Taps the first item' },\n    { pageId: 'home-flow-detail-screen', on: 'back', actionNote: 'Goes back to list' },\n  ],\n})\n`,
    [`${FLOW_BOOK_DIRNAME}/onboarding-flow/welcome-screen/WelcomePage.tsx`]: `import type { PageMeta } from '@flowkit/types'\nimport { useAppNav } from '@flowkit-shared/utils'\n\n// Two independent ways this page is reachable/interactive:\n// 1. Flow playback (F4) — the flowStory step matches this button by its id\n//    ('get-started'), so FlowMaster advances the flow on tap with no extra code.\n// 2. Screens tab (free exploration, no flow active) — onClick calls\n//    navigateTo() via useAppNav(), so the button also works standalone.\n//    useAppNav() picks the flow-aware navigateTo automatically when rendered\n//    inside a flow, so calling it unconditionally here never desyncs\n//    DashboardContext's view history from FlowEngine's step index.\nexport default function WelcomePage() {\n  const { navigateTo } = useAppNav()\n\n  return (\n    <div className="flex flex-col h-full bg-theme-base">\n      <div className="flex flex-col items-center justify-center flex-1 gap-4 p-6">\n        <div className="size-16 rounded-full bg-theme-blue-dim flex items-center justify-center">\n          <span className="text-2xl">👋</span>\n        </div>\n        <h1 className="text-ui-xl font-bold text-theme-text-primary text-center">\n          Welcome to FlowKit\n        </h1>\n        <p className="text-ui-sm text-theme-text-secondary text-center max-w-xs">\n          This workspace shows how pages read from db, use theme tokens, and wire interactions via\n          flowStory steps.\n        </p>\n      </div>\n      <div className="p-4 pb-8">\n        <button\n          id="get-started"\n          onClick={() => navigateTo('setup-screen')}\n          className="w-full px-3 py-2.5 rounded-md bg-theme-blue-dim text-theme-blue text-ui-sm font-medium"\n        >\n          Get Started\n        </button>\n      </div>\n    </div>\n  )\n}\n\nexport const pageMeta: PageMeta = {\n  label: 'Welcome Screen',\n  desc: 'Entry point — introduces the workspace and prompts user to begin.',\n  // Annotation badges (ephemeral review markers shown in the Screens panel) —\n  // replaces the old workspace-level annotation-tags sidecar file. Declare them\n  // directly on the screen they apply to instead:\n  // annotations: [{ label: 'new', color: 'green', icon: 'Star' }],\n}\n`,
    [`${FLOW_BOOK_DIRNAME}/onboarding-flow/setup-screen/SetupPage.tsx`]: `import type { PageMeta } from '@flowkit/types'\nimport { useDashboard } from '@flowkit-shared/contexts'\nimport { useAppNav } from '@flowkit-shared/utils'\n\nexport default function SetupPage() {\n  const { db } = useDashboard()\n  const { navigateTo } = useAppNav()\n\n  return (\n    <div className="flex flex-col h-full bg-theme-base">\n      <div className="flex items-center px-4 h-12 border-b border-theme-border-subtle">\n        <span className="text-ui-md font-medium text-theme-text-primary">Your Profile</span>\n      </div>\n      <div className="flex flex-col gap-3 p-4">\n        <div className="rounded-[10px] bg-theme-surface shadow-theme-card p-3 flex items-center gap-3">\n          <div className="size-10 rounded-full bg-theme-blue-dim flex items-center justify-center text-ui-sm font-bold text-theme-blue">\n            {db?.user?.name?.[0] ?? 'U'}\n          </div>\n          <div>\n            <p className="text-ui-sm font-medium text-theme-text-primary">{db?.user?.name ?? 'User'}</p>\n            <p className="text-ui-xs text-theme-text-muted">{db?.user?.email ?? ''}</p>\n          </div>\n        </div>\n        <div className="rounded-[10px] bg-theme-surface shadow-theme-card divide-y divide-theme-border-subtle">\n          {['Notifications', 'Privacy', 'Display'].map((item) => (\n            <div key={item} className="flex items-center justify-between px-3 py-2.5">\n              <span className="text-ui-sm text-theme-text-primary">{item}</span>\n              <span className="text-ui-xs text-theme-text-muted">›</span>\n            </div>\n          ))}\n        </div>\n      </div>\n      <div className="mt-auto p-4 pb-8">\n        <button\n          id="continue"\n          onClick={() => navigateTo('ready-screen')}\n          className="w-full px-3 py-2.5 rounded-md bg-theme-blue-dim text-theme-blue text-ui-sm font-medium"\n        >\n          Continue\n        </button>\n      </div>\n    </div>\n  )\n}\n\nexport const pageMeta: PageMeta = {\n  label: 'Setup Screen',\n  desc: 'Shows user profile read from db and setup options.',\n}\n`,
    [`${FLOW_BOOK_DIRNAME}/onboarding-flow/ready-screen/ReadyPage.tsx`]: `import type { PageMeta } from '@flowkit/types'\nimport { useDashboard } from '@flowkit-shared/contexts'\nimport { useAppNav } from '@flowkit-shared/utils'\n\nexport default function ReadyPage() {\n  const { db } = useDashboard()\n  const { navigateTo } = useAppNav()\n\n  return (\n    <div className="flex flex-col h-full bg-theme-base items-center justify-center gap-6 p-6">\n      <div className="size-16 rounded-full bg-theme-green-dim flex items-center justify-center">\n        <span className="text-2xl">✓</span>\n      </div>\n      <div className="flex flex-col items-center gap-2 text-center">\n        <h1 className="text-ui-xl font-bold text-theme-text-primary">You're all set</h1>\n        <p className="text-ui-sm text-theme-text-secondary">\n          {db?.user?.name ?? 'User'}, your workspace is ready.\n        </p>\n      </div>\n      <button\n        id="go-to-home"\n        onClick={() => navigateTo('home-screen')}\n        className="px-4 py-2.5 rounded-md bg-theme-blue-dim text-theme-blue text-ui-sm font-medium"\n      >\n        Go to Home\n      </button>\n    </div>\n  )\n}\n\nexport const pageMeta: PageMeta = {\n  label: 'Ready Screen',\n  desc: 'Onboarding complete — reads user name from db, prompts user to proceed.',\n}\n`,
    [`${FLOW_BOOK_DIRNAME}/home-flow/home-screen/HomePage.tsx`]: `import type { PageMeta } from '@flowkit/types'\nimport { useDashboard } from '@flowkit-shared/contexts'\nimport { useAppNav } from '@flowkit-shared/utils'\n\nexport default function HomePage() {\n  const { db } = useDashboard()\n  const { navigateTo } = useAppNav()\n  const items: Array<{ id: number; title: string; desc: string; status: string }> = db?.items ?? []\n\n  return (\n    <div className="flex flex-col h-full bg-theme-base">\n      <div className="flex items-center justify-between px-4 h-12 border-b border-theme-border-subtle">\n        <span className="text-ui-md font-medium text-theme-text-primary">Home</span>\n        <span className="text-ui-xs text-theme-text-muted">{items.length} items</span>\n      </div>\n      <div className="flex flex-col gap-2 p-4">\n        {items.map((item) => {\n          const badgeClass = item.status === 'active'\n            ? 'bg-theme-green-dim text-theme-green'\n            : 'bg-theme-amber-dim text-theme-amber'\n          return (\n            <div\n              key={item.id}\n              id={'item-' + item.id}\n              onClick={() => navigateTo('detail-screen')}\n              className="rounded-[10px] bg-theme-surface shadow-theme-card p-3 flex items-center justify-between gap-3 cursor-pointer"\n            >\n              <div className="flex flex-col gap-0.5 min-w-0">\n                <p className="text-ui-sm font-medium text-theme-text-primary truncate">{item.title}</p>\n                <p className="text-ui-xs text-theme-text-muted truncate">{item.desc}</p>\n              </div>\n              <span className={'text-ui-2xs font-bold uppercase tracking-[0.04em] px-1.5 py-0.5 rounded-full shrink-0 ' + badgeClass}>\n                {item.status}\n              </span>\n            </div>\n          )\n        })}\n      </div>\n    </div>\n  )\n}\n\nexport const pageMeta: PageMeta = {\n  label: 'Home Screen',\n  desc: 'Dashboard listing items from db.items with status badges.',\n}\n`,
    [`${FLOW_BOOK_DIRNAME}/home-flow/detail-screen/DetailPage.tsx`]: `import type { PageMeta } from '@flowkit/types'\nimport { useDashboard } from '@flowkit-shared/contexts'\nimport { useAppNav } from '@flowkit-shared/utils'\n\nexport default function DetailPage() {\n  const { db } = useDashboard()\n  const { navigateTo } = useAppNav()\n  const item = db?.items?.[0]\n\n  const badgeClass = item?.status === 'active'\n    ? 'bg-theme-green-dim text-theme-green'\n    : 'bg-theme-amber-dim text-theme-amber'\n\n  return (\n    <div className="flex flex-col h-full bg-theme-base">\n      <div className="flex items-center gap-2 px-4 h-12 border-b border-theme-border-subtle">\n        <button id="back" onClick={() => navigateTo('home-screen')} className="text-ui-sm text-theme-blue">← Back</button>\n        <span className="flex-1 text-center text-ui-sm font-medium text-theme-text-primary">Detail</span>\n        <div className="w-12" />\n      </div>\n      <div className="flex flex-col gap-4 p-4">\n        <div className="rounded-xl bg-theme-surface shadow-theme-card p-4 flex flex-col gap-3">\n          <div className="flex items-start justify-between gap-2">\n            <h2 className="text-ui-lg font-bold text-theme-text-primary">{item?.title ?? 'Item'}</h2>\n            <span className={'text-ui-2xs font-bold uppercase tracking-[0.04em] px-1.5 py-0.5 rounded-full shrink-0 ' + badgeClass}>\n              {item?.status}\n            </span>\n          </div>\n          <p className="text-ui-sm text-theme-text-secondary">{item?.desc ?? ''}</p>\n          <div className="pt-2 border-t border-theme-border-subtle">\n            <p className="text-ui-2xs font-bold uppercase tracking-[0.04em] text-theme-text-muted mb-1">Item ID</p>\n            <p className="text-ui-sm text-theme-text-primary">{item?.id ?? '—'}</p>\n          </div>\n        </div>\n      </div>\n    </div>\n  )\n}\n\nexport const pageMeta: PageMeta = {\n  label: 'Detail Screen',\n  desc: 'Detail view for a single item — reads from db.items[0] for demo.',\n}\n`,
    'lib/docs/overview.md': `# ${name} — Project Overview\n\n## What this is\n<!-- Describe the product and its purpose -->\n\n## Platform\n- **Target OS:** iOS / Android\n- **Primary device:** iPhone 16 Pro (393×852)\n- **Form factor:** Phone-first\n\n## Key chapters\n| Chapter | Pages | Purpose |\n|---|---|---|\n| onboarding-flow | welcome-screen → setup-screen → ready-screen | First-run onboarding |\n| home-flow | home-screen → detail-screen | Browse and inspect items |\n\n## Mock data\nSeed data lives in \`lib/data/db.ts\`. Named exports (\`user\`, \`items\`) are loaded into the platform \`db\` object.\nSimulator controls for mutating data at runtime are in \`lib/data/simulator.tsx\`.\n\n## Design system\nTokens live in \`lib/design-system/tokens.css\`. Shared UI components in \`lib/components/ui/\`.\n\n## Scaffold commands\n\`\`\`\nflowkit create:page --flow:<chapter> --name:<page>   # add a page\nflowkit create:chapter --name:<chapter>              # add a chapter\nflowkit create:component --name:<Name> --path:lib/components/ui\nflowkit add:step --flowStory:<id> --screen:<pageId> --action:"description"\n\`\`\`\n`,
    // NOTE: .agent/* files (INDEX, rules, platform) + the chosen agent's memory
    // file (CLAUDE.md / AGENTS.md / .cursor/rules) + project.md are generated by
    // scripts/platform/agent-sync.js from the single-source spec (agent-spec.js),
    // written by cmdNewWorkspace after this scaffold. Keep them OUT of this map
    // so there's one source of truth and `flowkit agent:sync` can re-emit them.
  }
}
